"""add is_verified to users

Revision ID: 6caf6bc12cc4
Revises: 3dc0dae326e0
Create Date: 2026-04-22 16:48:04.757069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6caf6bc12cc4'
down_revision: Union[str, Sequence[str], None] = '3dc0dae326e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('status', sa.String(), nullable=False))
    op.drop_constraint(op.f('role_role_name_key'), 'role', type_='unique')
    op.create_index(op.f('ix_student_info_matricula'), 'student_info', ['matricula'], unique=True)
    op.drop_constraint(op.f('user_role_role_id_fkey'), 'user_role', type_='foreignkey')
    op.create_foreign_key(None, 'user_role', 'role', ['role_id'], ['id'])
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_verified')
    op.drop_constraint(None, 'user_role', type_='foreignkey')
    op.create_foreign_key(op.f('user_role_role_id_fkey'), 'user_role', 'role', ['role_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_student_info_matricula'), table_name='student_info')
    op.create_unique_constraint(op.f('role_role_name_key'), 'role', ['role_name'], postgresql_nulls_not_distinct=False)
    op.drop_column('file', 'status')
    # ### end Alembic commands ###
