"""vincular qrcode con user_id

Revision ID: 8c9be5b32509
Revises: 97201a6e8520
Create Date: 2026-04-23 14:49:43.300742

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c9be5b32509'
down_revision: Union[str, Sequence[str], None] = '97201a6e8520'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file')
    op.add_column('qr_code', sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_qr_code_user_id'), 'qr_code', ['user_id'], unique=False)
    op.create_foreign_key(None, 'qr_code', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'qr_code', type_='foreignkey')
    op.drop_index(op.f('ix_qr_code_user_id'), table_name='qr_code')
    op.drop_column('qr_code', 'user_id')
    op.create_table('file',
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('modified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_group_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('pages', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['file_group_id'], ['file_group.id'], name=op.f('file_file_group_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('file_pkey'))
    )
    # ### end Alembic commands ###
