"""fix filegroup relations

Revision ID: bf3964f8757b
Revises: 6caf6bc12cc4
Create Date: 2026-04-22 22:30:40.096036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bf3964f8757b'
down_revision: Union[str, Sequence[str], None] = '6caf6bc12cc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_group',
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('print_job',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_group_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('kiosk_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('settings', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('final_cost', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['file_group_id'], ['file_group.id'], ),
    sa.ForeignKeyConstraint(['kiosk_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qr_code',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_group_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['file_group_id'], ['file_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qr_code_token'), 'qr_code', ['token'], unique=True)
    op.add_column('file', sa.Column('file_group_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('file', sa.Column('pages', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('file_user_id_fkey'), 'file', type_='foreignkey')
    op.create_foreign_key(None, 'file', 'file_group', ['file_group_id'], ['id'])
    op.drop_column('file', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'file', type_='foreignkey')
    op.create_foreign_key(op.f('file_user_id_fkey'), 'file', 'users', ['user_id'], ['id'])
    op.drop_column('file', 'pages')
    op.drop_column('file', 'file_group_id')
    op.drop_index(op.f('ix_qr_code_token'), table_name='qr_code')
    op.drop_table('qr_code')
    op.drop_table('print_job')
    op.drop_table('file_group')
    # ### end Alembic commands ###
